Move changelog check to Linux only job
Signed-off-by: Richard Whitehouse <richard.whitehouse@metaswitch.com>

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -6,14 +6,6 @@ rust:
 os:
 - linux
 - osx
-before_script:
-- |
-  ROOT_PACKAGE=swagger;
-  RUST_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -er "[.packages[] | select(.name == \"$ROOT_PACKAGE\") | .version][0]");
-  (grep -q "## \[$RUST_VERSION\] -" CHANGELOG.md || (echo "Missing CHANGELOG entry for version $RUST_VERSION"; /bin/false)) &&
-  (grep -q "\[Unreleased\]: .*/$RUST_VERSION\.\.\.HEAD$" CHANGELOG.md || (echo "Unreleased tag in CHANGELOG footer not updated for version $RUST_VERSION"; /bin/false)) &&
-  (grep -q "\[$RUST_VERSION\]: .*\.\.\.$RUST_VERSION$" CHANGELOG.md || (echo "Missing tag for version $RUST_VERSION in CHANGELOG footer"; /bin/false)) &&
-  echo "CHANGELOG is up-to-date for version $RUST_VERSION."
 matrix:
   allow_failures:
   - rust: nightly
@@ -34,6 +26,17 @@ matrix:
     script:
     - rustup component list --installed
     - cargo fmt -- --check
+  - rust: stable
+    os: linux
+    env: CHECK_CHANGELOG=1
+    script:
+    - |
+      ROOT_PACKAGE=swagger;
+      RUST_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -er "[.packages[] | select(.name == \"$ROOT_PACKAGE\") | .version][0]");
+      (grep -q "## \[$RUST_VERSION\] -" CHANGELOG.md || (echo "Missing CHANGELOG entry for version $RUST_VERSION"; /bin/false)) &&
+      (grep -q "\[Unreleased\]: .*/$RUST_VERSION\.\.\.HEAD$" CHANGELOG.md || (echo "Unreleased tag in CHANGELOG footer not updated for version $RUST_VERSION"; /bin/false)) &&
+      (grep -q "\[$RUST_VERSION\]: .*\.\.\.$RUST_VERSION$" CHANGELOG.md || (echo "Missing tag for version $RUST_VERSION in CHANGELOG footer"; /bin/false)) &&
+      echo "CHANGELOG is up-to-date for version $RUST_VERSION."
 branches:
   only:
   - staging
